name: 01 Paralelo action

on:
  push:
    branches: [main2]

jobs:
  print-hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hola mundo"

  print-hola:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hola"








