name: 03 Variable entorno action
on:
  push:
    branches: [main2]

jobs:
  print-hola-mundo:
    runs-on: ubuntu-latest
    env:
      SALUDO: "hola mundo"
    steps:
      - run: echo ${{ env.SALUDO }}