name: 04 Action outputs
on:
  push:
    branches: [main]

jobs:
    first-job:
        runs-on: ubuntu-latest
        outputs:
            my_variable: ${{ steps.set_output.outputs.my_variable }}
        steps:
            - name: Set output
              id: set_output
              run: echo "my_variable=hola mundo" >> $GITHUB_OUTPUT
            
            - name: Print output
              run: echo "The value of my_variable is ${{ steps.set_output.outputs.my_variable }}"

    second-job:
        runs-on: ubuntu-latest
        needs: first-job
        steps:
            - name: Print output from first job
              run: echo "The value of my_variable from first job is ${{ needs.first-job.outputs.my_variable }}"